
title: gardwired
email: greg@gardwired.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/"
url: "https://gardwired.gitlab.com" # the base hostname & protocol for your site
twitter_username: gardwired
github_username:  gardwired

# Build settings
markdown: kramdown
exclude: ["README.md"]